### Cear Artista
POST http://localhost:5000/api/artista/new
Content-Type: application/json

{
    "nombre": "Francisca valenzuela",
    "genero": [ "Jazz", "Pop", "Pop alternativo" ],
    "minCapacidad": 1000,
    "urlImagen": "http://todomejora.org/wp-content/uploads/2014/10/Francisca-Valenzuela-20141014-articulo-01_0-300x300.jpg"
            
    
}

### Cear Recinto
POST http://localhost:5000/api/recinto
Content-Type: application/json

{
    "nombre": "Cancha de Dichato",
    "sectores": [ {"nombre": "cancha", "capacidad": 10000}, {"nombre": "vip", "capacidad": 5000}],
    "ciudad": "Dichato",
    "urlImagen": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/64/25/ae/caption.jpg?w=300&h=300&s=1"
            
    
}

### Crear Concierto

POST http://localhost:5000/api/concierto
Content-Type: application/json

{
    "nombre": "Tómame Tour",
    "nombreArtista": "Francisca valenzuela",
    "nombreRecinto": "Cancha de Dichato",
    "fecha": "2021-11-23",
    "descripción": "Francisca Valenzuela se toma los escenarios del sur de chile con su nuevo tour Tómame que promociona su último álbum tajo Abierto",
    "precios": [ {"nombre": "cancha", "precio": 10000}, {"nombre": "vip", "precio": 5000}],
    "urlImagen": "http://soloartistaschilenos.cl/wp-content/uploads/2018/10/41669907_10156613042709801_7175841692401008640_n-300x300.jpg"

}

### Todos los  Conciertos

GET http://localhost:5000/api/concierto

### Concierto por Id

GET http://localhost:5000/api/concierto/porId/615477941bc6792b22fd1a73


### Comprar Entrada

PUT  http://localhost:5000/api/concierto/entradas/615477941bc6792b22fd1a73
Content-Type: application/json

{
    "nombreSector": "galeria",
    "cantidad": 1
    
            
    
}

### Array buscador

GET http://localhost:5000/api/matrizBuscador

### Lista de Artistas con Concierto

GET http://localhost:5000/api/artista/listaArtistas

### Lista de Ciudades con Concierto

GET http://localhost:5000/api/recinto/listaCiudades

### Lista de Generos con Concierto
GET http://localhost:5000/api/concierto/listaGeneros

### Conciertos por Artista

GET http://localhost:5000/api/concierto/porArtista/Metallica

### Conciertos por Genero

GET http://localhost:5000/api/concierto/porGenero/Pop

### Conciertos por Ciudad

GET http://localhost:5000/api/concierto/porCiudad/Valparaiso