### Cear Artista
POST http://localhost:5000/api/artista/new
Content-Type: application/json

{
    "nombre": "Daddy Yankee",
    "genero": [ "Reggeton", "Pop" ],
    "minCapacidad": 1000
            
    
}

### Cear Recinto
POST http://localhost:5000/api/recinto/new
Content-Type: application/json

{
    "nombre": "GGG Arena",
    "sectores": [ {"nombre": "galeria", "capacidad": 3000}, {"nombre": "platea", "capacidad": 300}, {"nombre": "asiento frontal", "capacidad": 500}, {"nombre": "frontal vip", "capacidad": 200 } ],
    "ciudad": "Santiago"
            
    
}

### Crear Concierto

POST http://localhost:5000/api/concierto/new
Content-Type: application/json

{
    "nombre": "Backstreet Boys World Tour",
    "nombreArtista": "Backstreet Boys",
    "nombreRecinto": "GGG Arena",
    "fecha": "2021-11-20",
    "descripción": "La última gira de la legendaria banda, promocionando su último album",
    "precios": [{"nombre":"galeria", "precio": 5000}]
    
            
    
}

### Todos los  Conciertos

GET http://localhost:5000/api/concierto/todos


### ComprarTicket

PUT  http://localhost:5000/api/concierto/tickets/6153912896f2f36c937c76bd
Content-Type: application/json

{
    "nombreSector": "galeria",
    "cantidad": 10
    
            
    
}

### Array buscador

GET http://localhost:5000/api/matrizBusador