### Cear Artista
POST http://localhost:5000/api/artista/new
Content-Type: application/json

{
    "nombre": "Daddy Yankee",
    "genero": [ "Reggeton", "Pop" ],
    "minCapacidad": 1000
            
    
}

### Cear Recinto
POST http://localhost:5000/api/recinto
Content-Type: application/json

{
    "nombre": "LOL Arena",
    "sectores": [ {"nombre": "galeria", "capacidad": 3000}, {"nombre": "platea", "capacidad": 300}, {"nombre": "asiento frontal", "capacidad": 500}, {"nombre": "frontal vip", "capacidad": 200 } ],
    "ciudad": "Arica"
            
    
}

### Crear Concierto

POST http://localhost:5000/api/concierto
Content-Type: application/json

{
    "nombre": "Daddy por siempre",
    "nombreArtista": "Daddy Yankee",
    "nombreRecinto": "Discord Arena",
    "fecha": "2021-11-23",
    "descripción": "A ella le gusta la gasolina y dale más gasolina",
    "precios": [{"nombre":"galeria", "precio": 2000}, {"nombre":"platea", "precio": 5000} ]

}

### Todos los  Conciertos

GET http://localhost:5000/api/concierto

### Concierto por Id

GET http://localhost:5000/api/concierto/porId/615477941bc6792b22fd1a73


### Comprar Entrada

PUT  http://localhost:5000/api/concierto/entradas/615477941bc6792b22fd1a73
Content-Type: application/json

{
    "nombreSector": "galeria",
    "cantidad": 1
    
            
    
}

### Array buscador

GET http://localhost:5000/api/matrizBuscador

### Lista de Artistas con Concierto

GET http://localhost:5000/api/artista/listaArtistas

### Lista de Ciudades con Concierto

GET http://localhost:5000/api/recinto/listaCiudades

### Lista de Generos con Concierto
GET http://localhost:5000/api/concierto/listaGeneros

### Conciertos por Artista

GET http://localhost:5000/api/concierto/porArtista/Metallica

### Conciertos por Genero

GET http://localhost:5000/api/concierto/porGenero/Pop

### Conciertos por Ciudad

GET http://localhost:5000/api/concierto/porCiudad/Valparaiso